version: "3"

services: 
    app:
        build: .
        command: npm start
        ports:
            - "3000:3000"
        restart: always
        volumes: 
            - .:/usr/app
    json:
        build: .
        command: npx json-server --watch data/db.json --port 3001
        ports:
          - "3001:3001"
        volumes:
          - .:/usr/app
        restart: always